# Generated by Django 5.0.6 on 2024-05-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("large_int", models.DecimalField(decimal_places=0, max_digits=100)),
                ("url", models.URLField()),
                ("eth_address", models.TextField()),
            ],
        ),
    ]
