# Generated by Django 5.0.6 on 2024-05-09 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("async_test", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="url",
        ),
    ]
